### ISSUE TITLE
Setting the width and hight of the preview area.

### ISSUE THREAD

**Issue by YashNonne** [saumitrabhave/qr-zbar-ane#46]
Many thanks for creating this native extension. It is very useful.

I have a handleResize function like this:

function handleResize(event:Event):void {
      var screenBounds:Rectangle = Screen.mainScreen.visibleBounds;
      var screenWidth:Number = Math.min(stage.fullScreenWidth, screenBounds.width);
      var screenHeight:Number = Math.min(stage.fullScreenHeight, screenBounds.height);

```
  appWidth = screenWidth;
  appHeight = screenHeight;
```

}

stage.addEventListener(Event.RESIZE, handleResize);

And I use appWidth and appHeight like this:

s.setConfig(Symbology.EAN13, Config.ENABLE, 1);
s.addEventListener(ScannerEvent.SCAN, onScan);
s.startPreview('rear', 0, 0, appWidth, appHeight - CloseButton.height);

The preview area fills up the entire screen instead of being CloseButton.height up from the bottom.

This seems to solve it:
s.startPreview('rear', 0, 0, appWidth / 2, (appHeight / 2) - (CloseButton.height / 2));

This will display a custom close button at the bottom of the screen. But I have to half all the width and height calculations. Is this right? Will this always work? I only have an iPhone to test on for now so I don't know if it will work on Android.

Here's a trace of handleResize before startPreview (it fired twice):
stage.fullScreenWidth: 640
stage.fullScreenHeight: 1136
screenBounds.width: 640
screenBounds.height: 1136
appWidth: 640
appHeight: 1136
stage.fullScreenWidth: 640
stage.fullScreenHeight: 1136
screenBounds.width: 640
screenBounds.height: 1136
appWidth: 640
appHeight: 1136

My phone's real screen dimensions is 1136 x 640.

I tried implementing this: https://github.com/saumitrabhave/qr-zbar-ane/blob/master/Example/src/com/sbhave/reader/tests/PreviewOrientation.as but it didn't change the results.

**Comment by mrfrasier** [comment]
On Android, I can set the width, height and position with no problem (only needing to invert the camera for some reason on rear).

On iOS, I seem to have to divide everything (x, y, width, height) by 2 to get it to appear properly. Something to keep in mind if you go cross-platform
