### ISSUE TITLE
iOS 64-bit

### ISSUE THREAD

**Issue by harry248** [saumitrabhave/qr-zbar-ane#47]
Are you planning to release an 64-bit compatible update?

**Comment by Nestordu** [comment]
I also need it, please quickly release

**Comment by saumitrabhave** [comment]
I have changed the native library to be universal (As Per http://labsdownload.adobe.com/pub/labs/flashruntimes/shared/air16_flashplayer16_releasenotes.pdf). Please verify and reopen in case of any issues.

**Comment by Nestordu** [comment]
Thank you very very much

**Comment by Nestordu** [comment]
Error: META-INF/ANE/iPhone-ARM/libQRZBar.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same.

I download the new ane , but it always has error!

Can you help me ?

**Comment by saumitrabhave** [comment]
Apologies, I did not verify correctly earlier. Issue is now fixed and ane will be arm64 compliant.

**Comment by Nestordu** [comment]
It is ok,  Thanks

**Comment by PortableSlots** [comment]
I think this change broke the AIR 15 support. I get this error when building it:

Error occurred while packaging the application:

```javascript
Undefined symbols for architecture armv7:
  "___udivmodsi4", referenced from:
      _qr_code_decode in libcom.sbhave.nativeExtensions.zbar.a(qrdec.o)
ld: symbol(s) not found for architecture armv7
Compilation failed while executing : ld64
```
