### ISSUE TITLE
API Change?

### ISSUE THREAD

**Issue by mannzer** [saumitrabhave/qr-zbar-ane#48]
Was there a major API change a while back?

While testing the 64 bit IOS code, I'm seeing a very different Scanner object: missing the launch and setTargetArea methods.

**Comment by saumitrabhave** [comment]
Yes, Please look at the samples at https://github.com/saumitrabhave/qr-zbar-ane/tree/master/Example/src/com/sbhave/reader/tests and documentation on https://github.com/saumitrabhave/qr-zbar-ane/blob/master/ASLib/src/com/sbhave/nativeExtensions/zbar/Scanner.as

Primary reason for the change was many requests to customise the UI around scanner view. This is now possible as the scanner is placed on the stage unlike earlier design where a separate native activity was launched.

**Comment by mannzer** [comment]
Thanks for the amazingly fast response!!
