### ISSUE TITLE
advise

### ISSUE THREAD

**Issue by Nestordu** [saumitrabhave/qr-zbar-ane#49]
Can you respectively build ane for ios and android?

I want to an smaller apk /ipa 

now the ane is 3.4 m , it is a little big.

Thanks

**Comment by saumitrabhave** [comment]
I dont think rebuilding ane for each platform is needed. I think the space increases because of the multiple static libraries included from ane in the final APK. 

You can create an unsigned apk and remove the assets you don't want to regenerate the apk.
