### ISSUE TITLE
App hang on ios using air16.

### ISSUE THREAD

**Issue by xastor** [saumitrabhave/qr-zbar-ane#52]
When I try to use the scanner on IOS using Air SDK 16 my application just hangs.  Is this a known issue?  Can I do anything to help debug the issue?

**Comment by saumitrabhave** [comment]
Can you please look at the device logs or actionscript logs for any errors, stacks trace or useful info?

**Comment by xastor** [comment]
Sorry, I was too quick to raise this issue.  I'm using mobile flex and the page that has the scanner integration also holds a datespinner component, which has a serious issue when used on air 16 : https://issues.apache.org/jira/browse/FLEX-34581
