### ISSUE TITLE
No way to determine whether user has granted camera access (ios)

### ISSUE THREAD

**Issue by harry248** [saumitrabhave/qr-zbar-ane#53]
When the user denied the access to the camera (on ios) I would like to show an alert. However the extension does no offer a method to check the access state.

**Comment by saumitrabhave** [comment]
Is this bug regarding https://bugbase.adobe.com/index.cfm?event=bug&id=3837401 ? Looks like a general AIR issue... Let me see if I can quickly add some code in ANE to surface this info.

**Comment by harry248** [comment]
Would be nice if you add a little check. Seems possible, see http://stackoverflow.com/questions/20464631/detect-permission-of-camera-on-ios

**Comment by saumitrabhave** [comment]
Will take this up.

**Comment by harry248** [comment]
Great! Thanks!

**Comment by saumitrabhave** [comment]
Fix has been done in startPreview method, it will ask for camera authorisation(if not asked already) and use the authorisation response in deciding whether to launch the camera preview or not.

startPreview can return false on iOS, if, the preview is already in progress OR the End User declined the Camera Access to application.
