### ISSUE TITLE
multi scan works test crash

### ISSUE THREAD

**Issue by smival** [saumitrabhave/qr-zbar-ane#54]
When I run "verify that multi scan works" and click the button I can see a rotated 90 degree camera and after next clicking the phone is down (device hard reboot). Also if you do nothing during camera working then after 20-30sec crash also happens! Android 5.1, Nexus4

**Comment by saumitrabhave** [comment]
If you are still facing this issue, please re-open the bug with complete adb logcat output of the crash.
