### ISSUE TITLE
Air 15 build broken.

### ISSUE THREAD

**Issue by PortableSlots** [saumitrabhave/qr-zbar-ane#55]
I think the AIR 16 (iOS 64) support commit broke the AIR 15 support. 
This is the error I get when building and app using the latest ANE:

``` javascript
Error occurred while packaging the application:
Undefined symbols for architecture armv7:
  "___udivmodsi4", referenced from:
      _qr_code_decode in libcom.sbhave.nativeExtensions.zbar.a(qrdec.o)
ld: symbol(s) not found for architecture armv7
Compilation failed while executing : ld64
```

I would guess that the iOS binary contains only one of the architectures instead of both.

Using a previous ANE is my current workaround:
https://raw.githubusercontent.com/saumitrabhave/qr-zbar-ane/217fe47d87a60ae013cc34d651ad3d9e91c71756/qreader.ane

**Comment by saumitrabhave** [comment]
i think its a iOS toolchain mismatch. my library is compiled with a different toolchain than whats bundled within AIR15 SDK. I would ask you to try ,
1. use the -platformsdk option to build your ipa with latest version on iOS SDK
2. Recompile the ANE with the AIR15 iOS toolchain.
