### ISSUE TITLE
Flash Pro CC 2015 & Adobe AIR 17.0 for Andriod

### ISSUE THREAD

**Issue by mc3dev** [saumitrabhave/qr-zbar-ane#56]
Hi,

I used the code from this site https://code.google.com/p/adobe-air-qr-barcode-zbar-ane/wiki/SampleUsage and included the qreader.ane in the Flash. It gives a warning message: "Warning: unable to load SWC qreader.ane" in the compiler errors. 

and at the bottom of the -app.xml file the <extension> tabs is empty, I manually added the following to the xml but it just does not work:

<extensions>
        <extensionID>com.sbhave.nativeExtensions.zbar</extensionID>
    </extensions>

Could you please advice what I was wrong?

Thank you very much for your help.

Regards,
Yu-Chang

**Comment by saumitrabhave** [comment]
I have created an Example in Flash, You can give it a try https://dl.dropboxusercontent.com/u/55311324/flash-example-qbar.zip ... Please be aware that it might have local paths which you might need to fix.

**Comment by mc3user** [comment]
Thank you very much. I will give it a try and may come back to you with some questions...
Is this working with iOS?
