### ISSUE TITLE
Flash Pro CC 2015 & Adobe AIR 17.0 for Android and iOS

### ISSUE THREAD

**Issue by mc3user** [saumitrabhave/qr-zbar-ane#57]
Hi, I used the Flash sample link you provided(https://dl.dropboxusercontent.com/u/55311324/flash-example-qbar.zip ), but I cannot find the "flex.swc" in the FlexSDK. I tried to download version 4.5.0, 4.5.1, and 4.6 with no luck. That file is no where to be found. 

Can you please let me know which FlexSDK you used for the Flash Pro sample and where to find the flex.swc? What is the purpose of flex.swc? 

Thank you for your help.

**Comment by mc3user** [comment]
Hi,

I used the Flash Pro sample to publish the Android version minus the "flex.swc" in the Library in Flash Pro CC 2015 & AIR for Android 17.0 and the sample works. Thank you very much. That gives me a good start.

However, when I tried the same file to publish with AIR for iOS 17.0 it gave an error. (see screenshot) Looks like the ANE does not support iOS 64.
![qreader](https://cloud.githubusercontent.com/assets/9010446/8582426/c8721708-2594-11e5-96ee-6413998b84bd.png)

I then switched to older version of Flash CS6 with AIR for iOS 15, but the publish was interrupted with the error message that "component_ronda.as" does not exist. I was not able to see this error message again for some reason. I was then able to publish the IPA without any error. However, the iOS IPA runs every step well until it needs to read the QR Code. The camera does not respond to the QR Code.

In the AIR for iOS mode, I ran "ctrl + Enter" to test movie and I got the following error code. Could you please provide help on how to get the iOS version to work either for Flash CC 2015, or for older version of Flash CS6? Thank you very much.


-----APP STARTING-----
TypeError: Error #2007: Parameter type must be non-null.
  at flash.events::EventDispatcher/addEventListener()
  at com.sbhave.reader.tests::SizeAndPosition/initialize()[C:\Users\xx\Downloads\flash-example-qbar\flash-example-qbar\src\com\sbhave\reader\tests\SizeAndPosition.as:57]
  at com.sbhave.reader::TestCase/run()[C:\Users\xx\Downloads\flash-example-qbar\flash-example-qbar\src\com\sbhave\reader\TestCase.as:66]
  at com.sbhave.reader::TestCase/onStatusChange()[C:\Users\xx\Downloads\flash-example-qbar\flash-example-qbar\src\com\sbhave\reader\TestCase.as:102]
  at flash.events::EventDispatcher/dispatchEventFunction()
  at flash.events::EventDispatcher/dispatchEvent()
  at com.sbhave.reader::TestCase/set status()[C:\Users\xx\Downloads\flash-example-qbar\flash-example-qbar\src\com\sbhave\reader\TestCase.as:50]
  at com.sbhave.reader::Harness/start()[C:\Users\xx\Downloads\flash-example-qbar\flash-example-qbar\src\com\sbhave\reader\Harness.as:72]
  at reader/start()[C:\Users\xx\Downloads\flash-example-qbar\flash-example-qbar\src\reader.as:78]
Test Movie terminated.

**Comment by saumitrabhave** [comment]
The 64 bit support error might be surfaced because the ane included in sample folder is older one. Please replace the same with the latest ane in the github repo

**Comment by mc3user** [comment]
Hi, I right-click to download the qreader.ane from the root of https://github.com/saumitrabhave/qr-zbar-ane, and added to the Flash Pro. When tried to publish with AIR for iOS 17.0 or 18.0, it shows this error message below:
![qreader2](https://cloud.githubusercontent.com/assets/9010446/8605071/9742560e-2650-11e5-8e78-e27731f80a65.png)

Please advice. Thank you for your help.

**Comment by mc3user** [comment]
Hi Saumitrabhave,
Thank you for the advice. I was able to redownload the zip file from the repository and replaced the ANE in the flash sample files you provided. Now I was able to publish the IPA usingFlash Pro CC 2015 AIR for iOS 18 without seeing any error.

However, when I ran the app on my iPad, everything seems to work up to the point when the camera is scanning the QR Code I created, nothing happened. The camera does not respond to the QR Code. 

Could you please advice? I really hope this willl work for the iOS before I can look into more of the controls. Thank you very much for your help.

**Comment by saumitrabhave** [comment]
Which test are you running exactly from the sample? Note that only SingleScanSimple and MultiScanSimple will actually scan the code. You can edit what test to run in what order by modifying this file (https://github.com/saumitrabhave/qr-zbar-ane/blob/master/Example/src/com/sbhave/reader/TestProvider.as)

**Comment by mc3user** [comment]
I didn't change the sample script. The iOS app runs with the following steps:
"Back Cam" button / "Front Cam" button / Camera size and position correct? "Yes" & "No" buttons / Verify that Camera Orientation is aligned with screen, "Back Cam" button / "Front Cam" button/ Did Camera aligned natually? "Yes" & "No" buttons/ Verify that Multi Scan Works "Click" button

At this point I tapped the "Click" button, the camera launches full screen. I pointed the camera to a QR Code, nothing happened. The camera does not respond and there is no way to close the camera and return back to the app. 

For some reason it did not display errors when the app was published but the camera is not reading the QR Code....

**Comment by mc3user** [comment]
I commented the code to test each one the "TestProvider.as" and published in AIR for iOS 18. Below each will bring up the camera full-screen but nothing happens when pointing the camera to the QR Code.... 
testsToRun.push(new SingleScanSimple());
testsToRun.push(new MultiScanSimple());

Do you have any advice? I really appreciated it.

**Comment by saumitrabhave** [comment]
I think single scan test is configured to read EAN barcodes only, multiscan should work for QR codes thoug
In multiscan you will have to scan the QR code 6 times to return to the app again. In iOS as of now, you will have to move the camera away(out of camera screen) from QR code and focus it back to scan it multiple times
As your app is working fine with ANE and its able to use all the APIs in ANE, i would suggest you start looking into the code and api documentation to create your own sample.... These tests are for my testing and may not make sense to you :)
