### ISSUE TITLE
NativeAndroid.jar missing from output

### ISSUE THREAD

**Issue by gcoope** [saumitrabhave/qr-zbar-ane#58]
When trying to compile the ANE using ant it cannot find NativeAndroid.jar which isn't included in the project - please advise if this is something I might be doing wrong?

**Comment by saumitrabhave** [comment]
You will have to generate NativeAndroid.jar, by packaging https://github.com/saumitrabhave/qr-zbar-ane/tree/master/NativeAndroid as jar

**Comment by gcoope** [comment]
My mistake - thanks!
