### ISSUE TITLE
Camera is rotated 90 degrees to the left on Android

### ISSUE THREAD

**Issue by mrfrasier** [saumitrabhave/qr-zbar-ane#60]
On iOS I use this code to set the orientation properly:

scanner.setCameraOrientation(( scanner.getCameraOrientation() - 180 + 360 ) % 360 );

Works, no issue. On Android, no matter what I set, the result from scanner.getCameraOrientation() is always 90 and the video feed is rotated to the left.

I've reviewed the code at https://github.com/saumitrabhave/qr-zbar-ane/blob/master/Example/src/com/sbhave/reader/tests/PreviewOrientation.as - however the issue seems to be that no matter what value I set, scanner.getCameraOrientation() ALWAYS returns 90. I've even tried just manually throwing in values without doing calculations based on orientation:

scanner.setCameraOrientation( 0 );
trace( "cam orientation:", scanner.getCameraOrientation() );
scanner.setCameraOrientation( 180 );
trace( "cam orientation:", scanner.getCameraOrientation() );
scanner.setCameraOrientation( -180 );
trace( "cam orientation:", scanner.getCameraOrientation() );

Trace result is always 90. Am I missing something?

**Comment by saumitrabhave** [comment]
Sorry for the confusing API name, though they look like getter/setter for same attribute, actually they are not. here is how getCameraOrientation and setCameraOrientation behave.

getCameraOrientation : Natively this is the value of http://developer.android.com/reference/android/hardware/Camera.CameraInfo.html#orientation , meaning this value gives you the orientation of the image that is being captured from camera focus with respect to natural orientation of device. Here is the quote from Android Docs,

The orientation of the camera image. The value is the angle that the camera image needs to be rotated clockwise so it shows correctly on the display in its natural orientation. It should be 0, 90, 180, or 270.

For example, suppose a device has a naturally tall screen. The back-facing camera sensor is mounted in landscape. You are looking at the screen. If the top side of the camera sensor is aligned with the right edge of the screen in natural orientation, the value should be 90. If the top side of a front-facing camera sensor is aligned with the right of the screen, the value should be 270.

This value by definition always remains same on a given device, and can not be changed.

setCameraOrientation: This sets the rotation angle for the preview on the screen. this does not change the value above, see http://developer.android.com/reference/android/hardware/Camera.html#setDisplayOrientation(int) .

**Comment by saumitrabhave** [comment]
On iOS getCameraOrientation is stubbed and returns a hardcoded value of 0.

**Comment by mrfrasier** [comment]
OK, that makes sense. However, not calling setCameraOrientation still yields the same as if I call set orientation with 0, 90, 180 and 270. Shouldn't it rotate, even if to another wrong position?

I'm testing on a Fire Phone and Nexus 6 for what it's worth. Also, it's a starling/stage3d project.

**Comment by saumitrabhave** [comment]
Can you provide the behaviour you observe when running https://github.com/saumitrabhave/qr-zbar-ane/blob/master/Example/src/com/sbhave/reader/tests/PreviewOrientation.as on your Android and iOS devices

**Comment by mrfrasier** [comment]
Thanks for the response. I ran reader.as as an application in full, and all looked OK except the QR scanning test. Ran it again commenting out all tests except PreviewOrientation and it worked fine. So I can only assume there's an issue with the way my project is set up.

Thanks!
