### ISSUE TITLE
starling uses

### ISSUE THREAD

**Issue by amihanya** [saumitrabhave/qr-zbar-ane#62]
hi,
i use with zbar.Scanner to scan QR code
and strarling, when i try to dispose the Scanner, its not hide, and dont see my starling. the screen is white and i cant remove the white screen.
how can i stop all the actions that zbar.Scanner make?
this is my code to remove the scanner:
<addr>
_scanner.stopPreview();
_scanner.dispose();
_scanner = null;
</addr>

**Comment by saumitrabhave** [comment]
is this issue happening on iOS or Android?

**Comment by amihanya** [comment]
hi,

this is android.

thanks!

**Comment by saumitrabhave** [comment]
Can you please help me understand the issue better.... 
Are you able to start the preview and scan the codes successfully?
Can you send me the logcat of your app when you call the stopPreview function.
Any screenshot/frames showing the issue would be helpful

**Comment by amihanya** [comment]
yes :)

I scan the QR and get the result, but whan i call to removeQr(); the camera close, but ths screen stay white and ican resume to my app.

This is my code:
	override protected function init():void 
		{
			if (Scanner.isSupported)
			{
				_scanner = new Scanner();
				trace(Symbology.EAN13);
				_scanner.setConfig(Symbology.EAN13,Config.ENABLE,1);

				// Only QR Code By default  
				_scanner.addEventListener(ScannerEvent.SCAN,onScan);

				// Multiple scans, until user presses back button to come back to the app.
				_scanner.startPreview("rear"); 
				
				_scanner.attachScannerToPreview();
			}else {
				getCode("http://www.biblecity.co.il/?positionId=1");
			}

		}
		
		private function onScan(event:ScannerEvent):void {
				 trace("Scan Event " + event.data);
				var size:* =  _scanner.getAvailablePreviewSizes();
				trace(size);
				_scanner.pausePreview();
				getCode(String(event.data));
				
				// _scanner.stopPreview();
		}
		
		private function getCode(url:String):void 
		{
			trace(url)
			var valuePairs:Array = url.substring(url.indexOf("?")+1).split("&");
			var map:Object = new Object();
			for (var i:int=0; i < valuePairs.length; i++) {
				var nextValuePair:Array = valuePairs[i].split("=");
				map[nextValuePair[0]] = nextValuePair[1];
			}
			if (map.positionId == assets.scanPostionId)
			{
					removeQr();
			}
		}

private function removeQr():void
{
                              _scanner.stopPreview();
					_scanner.dispose();
					_scanner = null;
					trace("assets.scanPostionId",assets.scanPostionId)
}

**Comment by saumitrabhave** [comment]
If I understand correctly, the code is working fine and removes the camera preview from the screen as expected right?

**Comment by amihanya** [comment]
yes.
but the remove is not perfect i still she a white screen, that i dont see before.
the Starling work on Stage3d (GPU), maybe its can help to understand the problem.

**Comment by mrfrasier** [comment]
Hi Ami, as a fellow starling/stage3d user, I want to ask: do you have starling set to automatically resume context? Maybe the context is being lost while the preview is shown and not being properly restored?

**Comment by amihanya** [comment]
I dont pause the Starling, i dont know if the scanner stop the starling. maybe can we ask daniel, if that can be the issue.

**Comment by mrfrasier** [comment]
Well in my own apps, things like loading the view finder or playing video often causes starling to lose context. Just offering it as a possible item of interest.

**Comment by amihanya** [comment]
Do you know how i can reconnect the Starling?
can i send you a simple project for test?

**Comment by mrfrasier** [comment]
See here: http://doc.starling-framework.org/v1.7/starling/core/Starling.html

> On some operating systems and under certain conditions (e.g. returning from system sleep), Starling's stage3D render context may be lost. Starling can recover from a lost context if the class property "handleLostContext" is set to "true". Keep in mind, however, that this comes at the price of increased memory consumption; Starling will cache textures in RAM to be able to restore them when the context is lost. (Except if you use the 'AssetManager' for your textures. It is smart enough to recreate a texture directly from its origin.)
