### ISSUE TITLE
Codabar not working

### ISSUE THREAD

**Issue by simonotten** [saumitrabhave/qr-zbar-ane#65]
Hi, 

I did several test with different barcode types and the all work fine, but for a project I need to use CODABAR.
According to Symbology.as (& ZBAR documentation) it is supposed to work, but I don't manage to scan it (tested with several codes). (for practical reasons, I'm currently testing with bitmaps.
Any idea why?

Thanks & regards.
simon

**Comment by saumitrabhave** [comment]
Can you try scanning the code through
https://itunes.apple.com/us/app/zbar-barcode-reader/id344957305?mt=8 app.

On Tuesday 22 March 2016, simonotten <notifications@github.com> wrote:

> Hi,
>
> I did several test with different barcode types and the all work fine, but
> for a project I need to use CODABAR.
> According to Symbology.as (& ZBAR documentation) it is supposed to work,
> but I don't manage to scan it (tested with several codes). (for practical
> reasons, I'm currently testing with bitmaps.
> Any idea why?
>
> Thanks & regards.
> simon
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/saumitrabhave/qr-zbar-ane/issues/65>
>


-- 
Saumitra Bhave VJTI, Mumbai

**Comment by simonotten** [comment]
Hi Saumitra, I'v just tried it, but it doesn't recognize the code either (scanning ean13 does work).

**Comment by saumitrabhave** [comment]
Looks like native library issue, also I am not sure if zbar is still
maintained or not. Looking for other libraries might be the option :( .

On Wednesday 23 March 2016, simonotten <notifications@github.com> wrote:

> Hi Saumitra, I'v just tried it, but it doesn't recognize the code either
> (scanning ean13 does work).
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/saumitrabhave/qr-zbar-ane/issues/65#issuecomment-199959474>
>


-- 
Saumitra Bhave VJTI, Mumbai

**Comment by simonotten** [comment]
Thanks Saumitra for the reply. 
I don't get it. I've installed the 'easy barcode app' (https://play.google.com/store/apps/details?id=org.magiclen.barcodescanner&hl=en) which uses the zbar lib, and it is able to scan codabar.  Is there a way to get it working in the ane?

**Comment by saumitrabhave** [comment]
If that is the case, you should be able to scan codebar with ane as well on
android. May codabar is enabled/implented for ios.

On Wednesday 23 March 2016, simonotten <notifications@github.com> wrote:

> Thanks Saumitra for the reply.
> I don't get it. I've installed the 'easy barcode app' (
> https://play.google.com/store/apps/details?id=org.magiclen.barcodescanner&hl=en)
> which uses the zbar lib, and it is able to scan codabar. Is there a way to
> get it working in the ane?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/saumitrabhave/qr-zbar-ane/issues/65#issuecomment-200227597>
>


-- 
Saumitra Bhave VJTI, Mumbai
