### ISSUE TITLE
PDF417 Barcode not scanning

### ISSUE THREAD

**Issue by ahbapAldirmaz** [saumitrabhave/qr-zbar-ane#69]
PDF 417 barcode not scannig. 

my code:

s = new Scanner();  
s.setConfig(Symbology.PDF417, Config.ENABLE, 1);
...etc.. and continue...

**Comment by saumitrabhave** [comment]
Please try scanning the same barcode on https://play.google.com/store/apps/details?id=org.magiclen.barcodescanner&hl=en 

Please re-open the issue and post your findings.

**Comment by makanmel** [comment]
Cannot scan too. Android 4.4 (Motorola XT1030).

Sample barcode: https://en.wikipedia.org/wiki/PDF417#/media/File:PDF417_Barcode.svg

Tried the https://play.google.com/store/apps/details?id=org.magiclen.barcodescanner but it is not supported by my device while random two application works good:
The https://play.google.com/store/apps/details?id=mobi.pdf417
and https://play.google.com/store/apps/details?id=com.scandit.demoapp

My Code:
`<?xml version="1.0" encoding="utf-8"?>
<s:Application xmlns:fx="http://ns.adobe.com/mxml/2009" xmlns:s="library://ns.adobe.com/flex/spark"
	creationComplete="onCreationComplete(event)" >
	<fx:Script><![CDATA[
		import com.sbhave.nativeExtensions.zbar.Config;
		import com.sbhave.nativeExtensions.zbar.Scanner;
		import com.sbhave.nativeExtensions.zbar.ScannerEvent;
		import com.sbhave.nativeExtensions.zbar.Symbology;

		import mx.events.FlexEvent;

		private var s:Scanner = new Scanner();

		private function onCreationComplete(event:FlexEvent):void
		{
			s.setConfig(Symbology.PDF417, Config.ENABLE, 1);
			s.addEventListener(ScannerEvent.SCAN, function (event:ScannerEvent):void
			{
				console.text = event.data;
			});
			s.startPreview("back", 0, 0, width, height / 2);
			s.attachScannerToPreview();
		}

		]]></fx:Script>
	<s:TextArea id="console" width="100%" height="50%" fontSize="36" fontFamily="Lucida Console"/>
</s:Application>
`

**Comment by esdebon** [comment]
Tested in Samsung J7, the PDF417 don´t work
